export const STRINGS = {
  app: {
    name: "CineReserve",
    tagline: "Your seat. Your story. Your cinema.",
  },
  nav: {
    home: "Home",
    movies: "Movies",
    myBookings: "My Bookings",
    profile: "Profile",
    settings: "Settings",
    login: "Sign In",
    signup: "Get Started",
    logout: "Sign Out",
    admin: "Admin",
  },
  home: {
    heroEyebrow: "Now Playing Tonight",
    heroTitle: "Where stories",
    heroTitleAccent: "come alive.",
    heroSubtitle:
      "Reserve the perfect seat in seconds. Premium screens, immersive sound, unforgettable nights.",
    heroCta: "Browse Movies",
    heroCtaSecondary: "Watch Trailer",
    nowShowing: "Now Showing",
    nowShowingSub: "Hand-picked premieres playing this week.",
    comingSoon: "Coming Soon",
    comingSoonSub: "The next big thing — mark your calendar.",
    stats: {
      movies: "Films streaming",
      halls: "Premium halls",
      guests: "Happy guests",
      rating: "Avg. rating",
    },
  },
  movies: {
    pageTitle: "All Movies",
    pageSub: "Find your next obsession.",
    searchPlaceholder: "Search movies, genres, actors…",
    noResults: "No movies match your search",
    bookNow: "Book Tickets",
    viewDetails: "View Details",
    duration: "Duration",
    rating: "Rating",
    genre: "Genre",
  },
  booking: {
    selectSeats: "Select Your Seats",
    screen: "Screen",
    available: "Available",
    selected: "Selected",
    booked: "Sold",
    premium: "Premium",
    confirmBooking: "Confirm Booking",
    seatsCount: (n: number) => `${n} seat${n !== 1 ? "s" : ""} selected`,
    total: "Total",
    pickAtLeastOne: "Pick at least one seat to continue",
    successTitle: "Your seats are locked in.",
    successSub: "We've sent the tickets to your inbox. Enjoy the show.",
    backToMovies: "Back to Movies",
  },
  toasts: {
    bookingSuccess: "🎉 Booking confirmed!",
    bookingFailed: "Couldn't complete booking.",
    seatTaken: "That seat was just taken. Pick another.",
  },
  footer: {
    tagline: "Made for movie lovers.",
    rights: "All rights reserved.",
    sections: {
      explore: "Explore",
      support: "Support",
      legal: "Legal",
    },
  },
} as const;
