/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoviesIndexRouteImport } from './routes/movies.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MoviesIdRouteImport } from './routes/movies.$id'
import { Route as BookingShowtimeIdRouteImport } from './routes/booking.$showtimeId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminShowtimesRouteImport } from './routes/admin.showtimes'
import { Route as AdminReservationsRouteImport } from './routes/admin.reservations'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminMoviesRouteImport } from './routes/admin.movies'
import { Route as AdminHallsRouteImport } from './routes/admin.halls'
import { Route as AdminGenresRouteImport } from './routes/admin.genres'
import { Route as BookingSuccessIdRouteImport } from './routes/booking.success.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MoviesIdRoute = MoviesIdRouteImport.update({
  id: '/movies/$id',
  path: '/movies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingShowtimeIdRoute = BookingShowtimeIdRouteImport.update({
  id: '/booking/$showtimeId',
  path: '/booking/$showtimeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShowtimesRoute = AdminShowtimesRouteImport.update({
  id: '/showtimes',
  path: '/showtimes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMoviesRoute = AdminMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHallsRoute = AdminHallsRouteImport.update({
  id: '/halls',
  path: '/halls',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGenresRoute = AdminGenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => AdminRoute,
} as any)
const BookingSuccessIdRoute = BookingSuccessIdRouteImport.update({
  id: '/booking/success/$id',
  path: '/booking/success/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/admin/genres': typeof AdminGenresRoute
  '/admin/halls': typeof AdminHallsRoute
  '/admin/movies': typeof AdminMoviesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/showtimes': typeof AdminShowtimesRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/$showtimeId': typeof BookingShowtimeIdRoute
  '/movies/$id': typeof MoviesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/booking/success/$id': typeof BookingSuccessIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/admin/genres': typeof AdminGenresRoute
  '/admin/halls': typeof AdminHallsRoute
  '/admin/movies': typeof AdminMoviesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/showtimes': typeof AdminShowtimesRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/$showtimeId': typeof BookingShowtimeIdRoute
  '/movies/$id': typeof MoviesIdRoute
  '/admin': typeof AdminIndexRoute
  '/movies': typeof MoviesIndexRoute
  '/booking/success/$id': typeof BookingSuccessIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/admin/genres': typeof AdminGenresRoute
  '/admin/halls': typeof AdminHallsRoute
  '/admin/movies': typeof AdminMoviesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/showtimes': typeof AdminShowtimesRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/$showtimeId': typeof BookingShowtimeIdRoute
  '/movies/$id': typeof MoviesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/booking/success/$id': typeof BookingSuccessIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bookings'
    | '/login'
    | '/profile'
    | '/signup'
    | '/admin/genres'
    | '/admin/halls'
    | '/admin/movies'
    | '/admin/reports'
    | '/admin/reservations'
    | '/admin/showtimes'
    | '/admin/users'
    | '/booking/$showtimeId'
    | '/movies/$id'
    | '/admin/'
    | '/movies/'
    | '/booking/success/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/login'
    | '/profile'
    | '/signup'
    | '/admin/genres'
    | '/admin/halls'
    | '/admin/movies'
    | '/admin/reports'
    | '/admin/reservations'
    | '/admin/showtimes'
    | '/admin/users'
    | '/booking/$showtimeId'
    | '/movies/$id'
    | '/admin'
    | '/movies'
    | '/booking/success/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bookings'
    | '/login'
    | '/profile'
    | '/signup'
    | '/admin/genres'
    | '/admin/halls'
    | '/admin/movies'
    | '/admin/reports'
    | '/admin/reservations'
    | '/admin/showtimes'
    | '/admin/users'
    | '/booking/$showtimeId'
    | '/movies/$id'
    | '/admin/'
    | '/movies/'
    | '/booking/success/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookingsRoute: typeof BookingsRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  BookingShowtimeIdRoute: typeof BookingShowtimeIdRoute
  MoviesIdRoute: typeof MoviesIdRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  BookingSuccessIdRoute: typeof BookingSuccessIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/movies/$id': {
      id: '/movies/$id'
      path: '/movies/$id'
      fullPath: '/movies/$id'
      preLoaderRoute: typeof MoviesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$showtimeId': {
      id: '/booking/$showtimeId'
      path: '/booking/$showtimeId'
      fullPath: '/booking/$showtimeId'
      preLoaderRoute: typeof BookingShowtimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/showtimes': {
      id: '/admin/showtimes'
      path: '/showtimes'
      fullPath: '/admin/showtimes'
      preLoaderRoute: typeof AdminShowtimesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/movies': {
      id: '/admin/movies'
      path: '/movies'
      fullPath: '/admin/movies'
      preLoaderRoute: typeof AdminMoviesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/halls': {
      id: '/admin/halls'
      path: '/halls'
      fullPath: '/admin/halls'
      preLoaderRoute: typeof AdminHallsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/genres': {
      id: '/admin/genres'
      path: '/genres'
      fullPath: '/admin/genres'
      preLoaderRoute: typeof AdminGenresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/booking/success/$id': {
      id: '/booking/success/$id'
      path: '/booking/success/$id'
      fullPath: '/booking/success/$id'
      preLoaderRoute: typeof BookingSuccessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminGenresRoute: typeof AdminGenresRoute
  AdminHallsRoute: typeof AdminHallsRoute
  AdminMoviesRoute: typeof AdminMoviesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminShowtimesRoute: typeof AdminShowtimesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGenresRoute: AdminGenresRoute,
  AdminHallsRoute: AdminHallsRoute,
  AdminMoviesRoute: AdminMoviesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminShowtimesRoute: AdminShowtimesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingsRoute: BookingsRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  BookingShowtimeIdRoute: BookingShowtimeIdRoute,
  MoviesIdRoute: MoviesIdRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  BookingSuccessIdRoute: BookingSuccessIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
